platform :ios, "11.0"
use_frameworks!

target 'wifilamp' do
	pod 'Alamofire'
    pod 'AwaitKit', '~> 3.0.1'
	pod 'QRCodeReader.swift'
    pod 'R.swift'
    pod 'SwiftLint'
    pod 'Swinject'
    pod 'SVProgressHUD', '~> 2.2.2'
end

post_install do |installer|
    # Set optim level to pods targets
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.name == 'Release'
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
                else
                config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
            end
        end
    end
end
