platform :ios, "9.0"

use_frameworks!

target 'wifilamp' do
	pod 'Alamofire'
    pod 'AwaitKit', '~> 3.0.1'
	pod 'QRCodeReader.swift'
    pod 'R.swift'
    pod 'SwiftLint'
    pod 'Swinject'
    pod 'SVProgressHUD', '~> 2.2.2'
end
